#- hosts: agent
#  remote_user: root
#  tasks:
  - name: Install EPEL Releases
    yum:
      name: epel-release
      state: present

  - name: Install Zabbix Repository
    yum:
      name: https://repo.zabbix.com/zabbix/{{zabbix_version}}/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      state: present


  - name: "Do a yum clean"
    shell: yum clean all
#    args:
#      warn: False
#    when: yum_repo_installed.changed
    become: yes
    tags:
      - skip_ansible_lint


  - name: Install Zabbix agent
    yum:
      name: zabbix-agent
      state: present

  - name: Start and enabled Zabbix agent processes
    service:
      name: zabbix-agent
      state: started
      enabled: True

  - name: Configure file /etc/zabbix/zabbix_agentd.conf
    template:
      src: "templates/zabbix_agentd.conf.j2"
      dest: "/etc/zabbix/zabbix_agentd.conf"
      owner: root
      group: root
      mode: 0644
    become: yes

#    ansible.builtin.replace:
#      path: /etc/zabbix/zabbix_agentd.conf
#      regexp: 'Server='
#      replace: 'Server=0.0.0.0/0, '
#
#  - name: Configure hostsname in file /etc/zabbix/zabbix_agentd.conf
#    ansible.builtin.replace:
#      path: /etc/zabbix/zabbix_agentd.conf
#     # after: 'Hostname= '
#      regexp: 'Hostname= '
#      replace: 'Hostname= {{item}}'
#    with_items: 
#    - 01
#    - 02
#    - 03
  - name: Restart Zabbix  agent processes
    service:
      name: zabbix-agent
      state: restarted

