# hay thay doi cac gia tri trong loop cho phu hop voi he thong cua ban
- hosts: fl004-srv-1
  tasks:
  - name: Create a new host or update an existing host's info
    local_action:
      module: zabbix_host
      server_url: http://172.16.15.5/zabbix
      login_user: Admin
      login_password: zabbix
      host_name: "{{ item.host }}"
      visible_name: "{{ item.visible }}"
      description: My ExampleHost Description
      host_groups:
        - Linux servers
      link_templates:
        - Template OS Linux by Zabbix agent
#        - Template Module Linux block devices by Zabbix agent
#        - Template Module Linux network interfaces by Zabbix agent

      status: disabled
      state: present
      inventory_mode: automatic
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{ item.ip }}"
          dns: ""
          port: 10050
    loop:
      - { host: '01', visible: 'ceph01', ip: '172.16.15.2' }
      - { host: '02', visible: 'ceph02', ip: '172.16.15.3' }
      - { host: '03', visible: 'ceph03', ip: '172.16.15.4' }
   
    when: ansible_facts['distribution'] == hdh and ansible_facts['os_family'] == suppliers 
