# Using autoregistration and Ansible with Zabbix: https://www.youtube.com/watch?v=cHCCoC-M31Q&t=936s
# may da cai dat san Apache (httpd service) va mariadb (hoac mysql)
---
- hosts: fl004-srv-1
  remote_user: root
  tasks:
  - name: Install EPEL Releases
    yum:
      name: epel-release
      state: present

  - name: Install Zabbix Repository
    yum:
      name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
      state: present

  - name: Install Zabbix server, frontend, agent
    yum: 
      name: ['zabbix-server-mysql', 'zabbix-agent', 'zabbix-get']
      state: present

  - name: Enable Red Hat Software Collections
    yum:
      name: centos-release-scl
      state: present

  - name: Edit file /etc/yum.repos.d/zabbix.repo and enable zabbix-frontend repository.
    replace:
      path: /etc/yum.repos.d/zabbix.repo
      regexp: enabled=0
      replace: enabled=1

  - name: Install Zabbix frontend packages.
    yum:
      name: ['zabbix-web-mysql-scl', 'zabbix-apache-conf-scl']
      state: present

  - name: Ensure service mariadb & httpd enabled and started
    service:
      name: '{{item}}'
      state: started
      enabled: True
    with_items:
    - mariadb
    - httpd

  - name: Install MySQL-python
    yum:
      name: MySQL-python
      state: present

  - name: Create database zabbix
    mysql_db:
      name: zabbix
      state: present
      collation: utf8_bin
      encoding: utf8

  - name: Copy DB Schema to Server
    copy:
      src: /root/zabbix-ansible/zabbix.sql
      dest: /root

  - name: Create user zabbix
    mysql_user:
      name: zabbix
      host: localhost
      password: zabbix
      priv: 'zabbix.*:ALL'
      state: present

  - name: >
      Import zabbix.sql with specific utf8 encoding,
      similar to mysql -u <username> --default-character-set=utf8 -p <password> < dump.sql
    community.mysql.mysql_db:
      name: zabbix
      collation: utf8_bin
      encoding: utf8
      state: import
      target: /root/zabbix.sql
      login_host: localhost
      login_user: zabbix
      login_password: zabbix
    failed_when: false


  - name: Start Zabbix server and agent processes
    service:
      name: '{{item}}'
      state: started
      enabled: True
    with_items:
    - zabbix-server
    - zabbix-agent
    - rh-php72-php-fpm

  - name: Edit file /etc/zabbix/zabbix_server.conf
    ansible.builtin.replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '# DBPassword='
      replace: 'DBPassword=zabbix'

#  - name: Edit file /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf uncomment and set the right timezone for you.
#    ansible.builtin.replace:
#      path: /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
#      regexp: ';'
#      replace: 'php_value[date.timezone] = Asia/Ho_Chi_Minh ;'

  - name: add myself to file /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
    lineinfile:
      path:  /etc/opt/rh/rh-php72/php-fpm.d/zabbix.conf
      regexp: '^; php_value[date.timezone] = Europe/Riga'
      line: php_value[date.timezone] = Asia/Ho_Chi_Minh

  - name: Configure PHP date.timezone
    ini_file:
      dest: /etc/opt/rh/rh-php72/php.ini
      section: Date
      option: date.timezone
      value: Asia/Ho_Chi_Minh
      backup: yes
    notify:
      - restart httpd server

#  handlers:
#  - name: restart httpd server
#    ansible.builtin.service:
#        name: httpd
#        state: restarted

  - name: Restart Zabbix server and agent processes
    service:
      name: '{{item}}'
      state: restarted
    with_items:
    - zabbix-server
    - zabbix-agent
    - rh-php72-php-fpm

